title: Juan Carielo
name: Juan Carielo
description: Hi, I'm back-end developer.
url: "https://juancarielo.github.io"
#baseurl: "/home"

author: Juan Carielo

image:
  path: /img/twitter.png
  height: 100
  width: 100

collections:
  portfolio:
    output: true
    permalink: /portfolio/:name

defaults:
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: porfolio

plugins:
  - jekyll-seo-tag
