title: Juan Carielo
name: Juan Carielo
description: Hi, I'm back-end developer.
url: "https://juancarielo.github.io"

author: Juan Carielo

collections:
  works:
    output: true
    permalink: /portfolio/:title
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title

defaults:
  - scope:
      path: ""
      type: "works"
    values:
      layout: article
  - scope:
      path: ""
      type: "posts"
    values:
      layout: article
