title: Juan Carielo
name: Juan Carielo

collections:
  portfolio:
    output: true
    permalink: /portfolio/:name

defaults:
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: porfolio

plugins:
  - jekyll-seo-tag
