title: Juan Carielo
name: Juan Carielo
description: Hi, I'm back-end developer.
url: "https://juancarielo.github.io"
author: Juan Carielo
google_analytics: 'UA-45662850-2'
collections:
  works:
    output: true
    permalink: /portfolio/:title
defaults:
  - scope:
      path: ""
      type: "works"
    values:
      layout: work
