title: Juan Carielo
name: Juan Carielo
author: Juan Carielo
description: Just a simple portfolio to share projects and content about Drupal.
theme_color: "#212529"
google_analytics: "G-SHZ0XQ2CFL"
url: "https://juancarielo.github.io"

permalink: pretty

collections:
  works:
    output: true
    permalink: /portfolio/:title

defaults:
  - scope:
      path: ""
    values:
      image: "/assets/dist/img/share.png"
  - scope:
      path: ""
      type: "works"
    values:
      layout: work

plugins:
  - jekyll-seo-tag
