title: Juan Carielo
name: Juan Carielo
author: Juan Carielo
description: Just a simple portfolio to share projects and content about Drupal.
theme_color: "#212529"
google_analytics: "G-SHZ0XQ2CFL"
url: "https://juancarielo.github.io"

permalink: pretty

timezone: America/Sao_Paulo

collections:
  works:
    output: true
    permalink: /portfolio/:title
  posts:
    output: true
    permalink: /blog/:title

defaults:
  - scope:
      path: ""
    values:
      image: "/assets/dist/img/share.png"
  - scope:
      path: "assets/dist/img/**"
    values:
      sitemap: false
  - scope:
      path: "assets/src/images/**"
    values:
      sitemap: false

  - scope:
      path: ""
      type: "works"
    values:
      layout: work
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
